### ISSUE TITLE
Question on your usage?

### ISSUE THREAD

**Issue by smcclstocks** [miki725/django-url-filter#17]
I really like what you're doing here & will probably be rolling this into a production app but I'm curious to know what your support situation is for this project. Do you currently use it in any production apps? Do you still consider yourself as actively maintaining this project? Do you follow along with latest deprecations of django & DRF & update this project & do you plan on continuing to do so?

I'm not asking because I expect you to do any of the above lol (you've already built something really nice & are generous enough to release it) but just curious where you stand. Thanks & feel free to close immediately.

**Comment by miki725** [comment]
First. Thanks for the support! Im glad you like the library. You literally made my day when I read your comment.

If the lib is production ready, I dont think any high traffic apps are using this lib, yet. I use it in my personal project and it seems to work well for me (after all I created it while working on a project). We are testing it at my work however it hasnt been merged to prod branch yet (maybe soon).

As for the support, I do try my best to maintain my open-source libs however you know how this goes - life intervenes... Im usually really excited about some idea, implement it and release it however later on its more difficult to find time to maintain the project. I usually do try to fix bugs if they are found and keep the libs compatible with newest Django/DRF versions, etc. It usually takes more time to implement new features so they probably wont come as frequently. If people however will need any features and express their thoughts via GH issues, I will definitely prioritize those. That being said, I do accept PRs so if others will be willing to contribute via PRs, improving docs, etc that will be awesome too!

Let me know if the answer is satisfactory so that we can close the ticket.

**Comment by smcclstocks** [comment]
Sounds great man, thanks for getting back. I'm up in the air still on whether I'll use this or go with my own trying to use DRF serializers for validations. Not sure yet but definitely you answered great.
