### ISSUE TITLE
Django backend does not return distinct results

### ISSUE THREAD

**Issue by miki725** [miki725/django-url-filter#26]
When filtering on many-to-one models on the foreign key model, it causes a join which then returns non-distinct results. Found as part of looking at #18.

**Comment by nesterenko-d** [comment]
@miki725 Hello, thanks for your library. I think it is a bad idea to add DISTINCT to all queries because this operation really expensive for a database. 

I'm using your library for filtering a table with 3 millions of rows and the DISTINCT really slow down a query.

I guess that DISTINCT have to be optional and moved in each application on view level.

**Comment by miki725** [comment]
@nesterenko-d thats fair. Although that will complicate view logic as if you join one-to-many tables for a filter clause (which is optional), without distinct multiple records will be returned. For now compromise could be to only do distinct when joins are made. Otherwise not to apply distinct.

**Comment by selimt** [comment]
Hi, is there a workaround for this? We also ran into a problem where automatically adding distinct when calling self.filter_queryset(queryset) slows down the query considerably if the filter doesn't contain criteria to cull down the result set too much. Sometimes we add a limit to get the first few entries so we don't need to retrieve all the rows.

Thanks
-Selim

**Comment by miki725** [comment]
https://github.com/miki725/django-url-filter/pull/71 should address this. anybody willing to give it a try?

**Comment by selimt** [comment]
Hi, I tried this change and it works great. I upgraded from 0.3.5 to this version so I had to make some more changes to the code since you now have more strict checking for the query dict and I was passing some values that were not supported by the url_filter but I worked around it.

Thanks for this.
-Selim

**Comment by miki725** [comment]
thanks @selimt . just made a release so can pull from pypi now.

as for strict mode, you can always change strict mode to whatever works for you - https://github.com/miki725/django-url-filter/blob/master/url_filter/constants.py#L6

**Comment by selimt** [comment]
Thanks, the strict mode doesn’t seem to work like it used to though. It used to ignore any invalid filters we pass in the url.

When we add status__has_any_keys=‘foo,bar’, it returns an empty queryset. Since url_filter doesn’t support has_any_keys for json fields, we are handling it ourselves.

What we now do is create a copy of the request.GET and then pop the invalid filters from the QueryDict so that url_filter doesn’t complain. Is there a better way?

Thanks
-Selim

**Comment by miki725** [comment]
best I can think of is you can create a callable filter which mimicks json filtering.

Im still contemplating how to add general json field support since json filters can be nested:

```
?relation__jsonfield__lookup__anotherlookup=value
```

currently that breaks how its being validated since the assumption was that you can have at most one lookup. it is a pretty useful feature for people who use json fields so when I have some free time Ill try to add something which allows for that.

also same will apply to some of postgis lookups...

**Comment by selimt** [comment]
That would be great. Our json lookups are not nested so simple support such as relation__jsonfield__lookup would work us. I’ll look into adding a callable filter.

-Selim
